apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audit
  template:
    metadata:
      labels:
        app: audit
    spec:
      containers:
        - name: audit-container
          image: cyrilcuvier/audit:latest  # Image contenant déjà le script
          env:
            - name: TOKEN
              value: "your_bearer_token_here"  # Remplace par ton token ici
