apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit-script-deployment
  labels:
    app: audit-script
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audit-script
  template:
    metadata:
      labels:
        app: audit-script
    spec:
      containers:
      - name: audit-script
        image: "docker.io/cyrilcuvier/audit:latest"
        env:
          - name: TOKEN
            value: "{{ .Values.token }}"
